import { useEffect, useState } from "react";
import QRCode from "qrcode";

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5000";
const mapsUrl = "https://www.google.com/maps/search/?api=1&query=Grand+Celebration+Ground+Pune";
const whatsappUrl = "https://wa.me/919000000000?text=Hi%20Kesariya%20Garba%2C%20I%20want%20to%20book%20tickets.";

const images = [
  { title: "Garba Circle", src: "https://images.pexels.com/photos/17264037/pexels-photo-17264037.jpeg?auto=compress&cs=tinysrgb&w=1400" },
  { title: "Celebration", src: "https://images.pexels.com/photos/28489406/pexels-photo-28489406.jpeg?auto=compress&cs=tinysrgb&w=1400" },
  { title: "Navrang", src: "https://images.pexels.com/photos/18983063/pexels-photo-18983063.jpeg?auto=compress&cs=tinysrgb&w=1400" },
  { title: "Festival Colours", src: "https://images.pexels.com/photos/8000319/pexels-photo-8000319.jpeg?auto=compress&cs=tinysrgb&w=1400" }
];
const fallbackEvents = [
  { id: 1, title: "Kesariya Navrang 2026", description: "Five nights of Garba, Dandiya, live music, colour and celebration.", event_date: "2026-10-24T19:00:00+05:30", venue: "Grand Celebration Ground", city: "Pune", price: 499, available_seats: 2500 },
  { id: 2, title: "Kesariya Dandiya Under The Stars", description: "Open-air Dandiya with folk percussion and a family dance floor.", event_date: "2026-10-31T19:30:00+05:30", venue: "Riverside Lawns", city: "Pune", price: 599, available_seats: 1800 }
];
const passes = [
  ["COUPLE DAY PASS",1500,"2 people · one evening", "wine"],
  ["5-DAY SEASON PASS",5000,"All five Navrang nights", "gold"],
  ["PREMIUM / CORPORATE PASS",50000,"Premium hospitality · group access", "violet"]
];
const faqs = [
  ["What does my ticket include?","Entry to the selected celebration and a digital QR pass for every confirmed booking."],
  ["Can I show the QR ticket on my phone?","Yes. Keep the QR visible at entry. A used QR cannot be accepted twice."],
  ["Is payment real or demo?","Demo payment is enabled by default. Razorpay can be connected later."],
  ["Is parking available?","Yes. Current demo venue data includes parking and a map link."],
  ["Can I book for a group?","Yes. Use the contact form for group and corporate requirements."]
];

const formatDate = value => new Date(value).toLocaleString("en-IN", { dateStyle:"full", timeStyle:"short" });
function useCountdown(target){
  const [t,setT]=useState({days:0,hours:0,minutes:0,seconds:0});
  useEffect(()=>{const tick=()=>{const n=Math.max(0,Math.floor((new Date(target)-Date.now())/1000));setT({days:Math.floor(n/86400),hours:Math.floor(n/3600)%24,minutes:Math.floor(n/60)%60,seconds:n%60})};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[target]);return t;
}

function Nav({onAdmin}){
  const [open,setOpen]=useState(false);
  const links=[["HOME","home"],["ABOUT","about"],["EVENT","event"],["TICKETS","tickets"],["GALLERY","gallery"],["CONTACT","contact"]];
  return <header className="site-nav"><a href="#home" className="brand-mark"><span className="brand-sun">✦</span><span><b>KESARIYA</b><small>NAVRANG 2026</small></span></a><nav className={open?"nav-links open":"nav-links"}>{links.map(([l,id])=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)}>{l}</a>)}<button onClick={onAdmin}>ADMIN</button></nav><a className="nav-cta" href="#tickets">BOOK TICKETS</a><button className="menu-toggle" onClick={()=>setOpen(!open)}>☰</button></header>;
}

function Hero({event,onBook}){
  const c=useCountdown(event?.event_date||fallbackEvents[0].event_date);
  return <section id="home" className="dark-page hero-page"><div className="cosmic-ring ring-a"/><div className="cosmic-ring ring-b"/><div className="hero-grid"><div className="hero-copy"><span className="micro-label">THE NAVRANG FEELING</span><h1><span>MOMENTS IN MOTION.</span><strong>MEMORIES IN COLOUR.</strong></h1><p>Five nights of Navrang. One shared rhythm. A premium Garba and Dandiya experience where tradition meets celebration.</p><div className="hero-actions"><button className="gold-button" onClick={onBook}>ENTER THE CIRCLE ↗</button><a className="text-link" href="#event">DISCOVER THE JOURNEY ↓</a></div><div className="countdown-row">{Object.entries(c).map(([k,v])=><div key={k}><b>{String(v).padStart(2,"0")}</b><span>{k}</span></div>)}</div></div><div className="hero-art"><div className="mandala-frame"><img src={images[1].src} alt="Garba celebration"/><div className="mandala-overlay"/><div className="date-stamp"><b>24</b><span>OCT</span></div><div className="art-caption">A CELEBRATION WITH PURPOSE</div></div></div></div></section>;
}
function About(){return <section id="about" className="dark-page about-page"><div className="section-intro"><span>THE INVITATION</span><h2>MORE THAN A<br/><em>FESTIVAL.</em></h2><p>A SHARED SPIRITUAL RHYTHM.</p></div><div className="about-grid"><div className="portrait-card"><img src={images[2].src} alt="Festive dancer"/><div className="card-label">TRADITION · COLOUR · RHYTHM</div></div><div className="about-copy"><div className="story-line"><b>01</b><div><small>THE INVITATION</small><p>Kesariya Navrang is imagined as a premium five-night Navratri and Dandiya celebration bringing together culture, music, entertainment, community and brands.</p></div></div><div className="story-line"><b>02</b><div><small>THE EXPERIENCE</small><p>Move through a living mandala of colour, attire, ritual, live percussion, lights and a circular dance floor.</p></div></div></div></div></section>}
function EventJourney({event,onBook}){const nights=["VRINDAVAN","RAJASTHANI ROYAL","GUJARATI RANG","BOLLYWOOD BEATS","GRAND NAVRANG"];return <section id="event" className="dark-page journey-page"><div className="section-intro centered"><span>THE SPIRITUAL JOURNEY</span><h2>FIVE NIGHTS.<br/><em>ONE EVOLVING SOUL.</em></h2><p>Move through the mandala and awaken each night's distinct ritual, colour, attire and energy.</p></div><div className="orbit-stage"><div className="orbit orbit-1"/><div className="orbit orbit-2"/><div className="orbit-center"><img src={images[0].src} alt="Garba circle"/><span>GARBA CIRCLE</span></div>{nights.map((n,i)=><div key={n} className={`night-node node-${i+1}`}><small>DAY {i+1}</small><b>{n}</b></div>)}</div><div className="journey-details"><div><small>FEATURED EVENT</small><h3>{event?.title}</h3><p>{formatDate(event?.event_date)} · {event?.venue}</p></div><button className="gold-button" onClick={onBook}>CHOOSE YOUR NIGHT ↗</button></div></section>}
function Tickets({onBook}){return <section id="tickets" className="dark-page tickets-page"><div className="section-intro centered"><span>CHOOSE YOUR ENTRY</span><h2>YOUR PASS.<br/><em>YOUR CIRCLE.</em></h2><p>One night, all five, or premium hospitality — every pass opens a different Navrang story.</p></div><div className="ticket-grid">{passes.map((p,i)=><article key={p[0]} className={`nav-ticket ${p[3]}`}>{i===1&&<div className="ribbon">BEST VALUE</div>}<div className="ticket-image"><img src={images[i].src} alt={p[0]}/></div><div className="ticket-content"><small>{i===0?"ONE NIGHT":i===1?"ALL FIVE NIGHTS":"PREMIUM HOSPITALITY"}</small><h3>{p[0]}</h3><strong>₹{p[1].toLocaleString("en-IN")}</strong><p>{p[2]}</p><button onClick={()=>onBook({...fallbackEvents[0],title:p[0],price:p[1]})}>SELECT PASS ↗</button></div></article>)}</div></section>}
function Gallery(){const loop=[...images,...images];return <section id="gallery" className="dark-page gallery-page"><div className="section-intro gallery-intro"><span>THE NAVRANG FEELING</span><h2>MOMENTS IN MOTION.<br/><em>MEMORIES IN COLOUR.</em></h2></div><div className="gallery-marquee"><div className="gallery-track">{loop.map((x,i)=><a className="gallery-card" key={i} href={x.src} target="_blank" rel="noreferrer"><img src={x.src} alt={x.title}/><span>{x.title}</span></a>)}</div></div><div className="gallery-controls"><span>LIVE MOTION GALLERY</span><span>01 — 04</span></div></section>}
function FAQ(){const [open,setOpen]=useState(0);return <section id="faq" className="faq-page"><div className="section-intro centered"><span>GOOD TO KNOW</span><h2>QUESTIONS.<br/><em>ANSWERED.</em></h2></div><div className="faq-box">{faqs.map(([q,a],i)=><button key={q} onClick={()=>setOpen(open===i?-1:i)}><span>{q}</span><b>{open===i?"−":"+"}</b>{open===i&&<p>{a}</p>}</button>)}</div></section>}
function Contact({onSent}){const [f,setF]=useState({name:"",email:"",phone:"",message:""});const [busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);try{const r=await fetch(`${API_URL}/api/inquiries`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(f)});const d=await r.json();onSent(r.ok?d.message:"Demo inquiry received.");}catch{onSent("Demo inquiry received. The organizer will follow up shortly.")}finally{setBusy(false);setF({name:"",email:"",phone:"",message:""})}};return <section id="contact" className="contact-page"><div className="contact-wrap"><div><span className="gold-label">JOIN THE CIRCLE</span><h2>LET'S MAKE<br/><em>IT FESTIVE.</em></h2><p>For group bookings, sponsorships, partnerships or event questions, reach the Kesariya team.</p><div className="contact-list"><a href={whatsappUrl} target="_blank" rel="noreferrer">WHATSAPP <b>+91 90000 00000</b></a><a href="mailto:hello@kesariya.test">EMAIL <b>hello@kesariya.test</b></a><a href={mapsUrl} target="_blank" rel="noreferrer">VENUE <b>Grand Celebration Ground ↗</b></a></div></div><form onSubmit={submit} className="dark-form"><input required placeholder="Your name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input required type="email" placeholder="Email address" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input placeholder="Phone number" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/><textarea required rows="5" placeholder="Tell us what you need" value={f.message} onChange={e=>setF({...f,message:e.target.value})}/><button disabled={busy} className="gold-button">{busy?"SENDING…":"SEND INQUIRY ↗"}</button></form></div></section>}
function BookingModal({event,onClose,onSuccess}){const [qty,setQty]=useState(1);const [f,setF]=useState({name:"",email:"",phone:""});const [busy,setBusy]=useState(false);const total=Number(event.price)*qty;const submit=async e=>{e.preventDefault();setBusy(true);const code=`KG-${Date.now().toString().slice(-6)}`;const qr=await QRCode.toDataURL(JSON.stringify({bookingCode:code,event:event.title,name:f.name,quantity:qty}));onSuccess({code,qr,event,total,f});setBusy(false)};return <div className="modal-backdrop"><form className="booking-modal" onSubmit={submit}><button type="button" className="modal-close" onClick={onClose}>×</button><span className="gold-label">RESERVE YOUR CIRCLE</span><h2>{event.title}</h2><p className="modal-meta">{formatDate(event.event_date)} · {event.venue}</p><div className="form-grid"><input required placeholder="Full name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input required type="email" placeholder="Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input required placeholder="Phone" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/><select value={qty} onChange={e=>setQty(Number(e.target.value))}>{Array.from({length:10},(_,i)=>i+1).map(n=><option key={n} value={n}>{n} ticket{n>1?"s":""}</option>)}</select></div><div className="booking-total"><span>Total</span><strong>₹{total.toLocaleString("en-IN")}</strong></div><button disabled={busy} className="gold-button full">{busy?"CONFIRMING…":"CONTINUE WITH DEMO PAYMENT ↗"}</button><small className="demo-note">Demo mode: no real money is charged.</small></form></div>}
function Confirmation({data,onClose}){return <div className="modal-backdrop"><div className="confirmation-card"><div className="success-ring">✓</div><span className="gold-label">BOOKING CONFIRMED</span><h2>Your circle is reserved.</h2><p>{data.event.title} · {data.f.name}</p><div className="booking-code">{data.code}</div><img className="qr-image" src={data.qr} alt="Booking QR code"/><p className="small-note">Show this QR at entry.</p><button className="gold-button full" onClick={onClose}>DONE</button></div></div>}
function Admin({onClose}){const [login,setLogin]=useState(false);const [email,setEmail]=useState("");const [pass,setPass]=useState("");const [tab,setTab]=useState("dashboard");const [notice,setNotice]=useState("");if(!login)return <div className="modal-backdrop"><form className="admin-login" onSubmit={e=>{e.preventDefault();if(email==="admin@kesariya.test"&&pass==="admin123")setLogin(true);else setNotice("Use admin@kesariya.test / admin123")}}><button type="button" className="modal-close" onClick={onClose}>×</button><span className="gold-label">ORGANIZER CONSOLE</span><h2>Admin access.</h2><input required type="email" placeholder="admin@kesariya.test" value={email} onChange={e=>setEmail(e.target.value)}/><input required type="password" placeholder="admin123" value={pass} onChange={e=>setPass(e.target.value)}/>{notice&&<div className="error-box">{notice}</div>}<button className="gold-button full">LOGIN ↗</button></form></div>;return <div className="modal-backdrop"><div className="admin-panel"><button className="modal-close" onClick={onClose}>×</button><aside><span className="gold-label">KESARIYA</span><h2>Organizer</h2>{["dashboard","bookings","qr","inquiries"].map(x=><button key={x} className={tab===x?"admin-tab active":"admin-tab"} onClick={()=>setTab(x)}>{x.toUpperCase()}</button>)}</aside><main><span className="gold-label">LIVE DEMO</span><h2>{tab}</h2>{tab==="dashboard"&&<div className="admin-stats"><div><small>BOOKINGS</small><b>128</b></div><div><small>TICKETS SOLD</small><b>346</b></div><div><small>CHECKED IN</small><b>219</b></div><div><small>INQUIRIES</small><b>17</b></div></div>}{tab==="bookings"&&<div className="admin-list">{["KG-2401","KG-2402","KG-2403","KG-2404"].map((x,i)=><div key={x}><b>{x}</b><span>{["Aarav Mehta","Riya Shah","Kabir Patil","Meera Joshi"][i]}</span><em>Confirmed</em></div>)}</div>}{tab==="qr"&&<div className="qr-admin"><p>Enter a booking code to test the entry gate.</p><input placeholder="KG-2401"/><button className="gold-button" onClick={()=>setNotice("QR accepted. Duplicate scans are rejected.")}>VERIFY QR ↗</button>{notice&&<div className="success-box">{notice}</div>}</div>}{tab==="inquiries"&&<div className="admin-list"><div><b>Group booking</b><span>Corporate Dandiya package enquiry</span><em>New</em></div><div><b>Sponsorship</b><span>Brand partnership enquiry</span><em>New</em></div></div>}</main></div></div>}

export default function App(){const [events,setEvents]=useState(fallbackEvents);const [booking,setBooking]=useState(null);const [confirmation,setConfirmation]=useState(null);const [admin,setAdmin]=useState(false);const [toast,setToast]=useState("");useEffect(()=>{fetch(`${API_URL}/api/events`).then(r=>r.ok?r.json():[]).then(d=>{if(Array.isArray(d)&&d.length)setEvents(d)}).catch(()=>{});},[]);const event=events[0];const toastNow=m=>{setToast(m);setTimeout(()=>setToast(""),4000)};return <div className="app-shell"><Nav onAdmin={()=>setAdmin(true)}/><Hero event={event} onBook={()=>setBooking(event)}/><div className="gold-ticker"><div>✦ NAVRANG 2026 ✦ FIVE NIGHTS OF GARBA ✦ DANDIYA UNDER THE STARS ✦ MUSIC · COLOUR · COMMUNITY ✦ NAVRANG 2026 ✦</div></div><About/><EventJourney event={event} onBook={()=>setBooking(event)}/><Tickets onBook={setBooking}/><Gallery/><FAQ/><Contact onSent={toastNow}/><footer className="site-footer"><span>KESARIYA NAVRANG 2026</span><span>RANG · RAAS · RHYTHM</span><a href="#home">BACK TO TOP ↑</a></footer>{booking&&<BookingModal event={booking} onClose={()=>setBooking(null)} onSuccess={d=>{setBooking(null);setConfirmation(d)}}/>}{confirmation&&<Confirmation data={confirmation} onClose={()=>setConfirmation(null)}/>} {admin&&<Admin onClose={()=>setAdmin(false)}/>} {toast&&<div className="toast">{toast}</div>}</div>}
